#!/usr/bin/env bash
# Idempotent setup for the Google Stitch MCP server in Claude Code on the web
# (ephemeral Linux containers). Ties the Stitch identity to a single Google
# account via gcloud OAuth. Safe to run repeatedly. NEVER prints access tokens.
#
# It only does the work that is missing:
#   1. Installs the gcloud CLI from the allowlisted storage.googleapis.com
#      mirror (the normal dl.google.com installer is blocked by the network
#      allowlist in this environment).
#   2. Verifies gcloud runs.
#   3. (Re)generates the proxy wrapper + a direct helper (no secrets in them;
#      the OAuth token is minted at call time).
#   4. Writes .mcp.json in the repo root (kept gitignored) pointing at the proxy.
#   5. Checks (and enables, if logged in) stitch.googleapis.com on the quota
#      project.
#   6. Prints the exact one-time OAuth step when no gcloud login is present.

set -uo pipefail

# ---- Config (override via environment if needed) ---------------------------
STITCH_ACCOUNT="${STITCH_ACCOUNT:-slavkofilipovich@gmail.com}"
GCP_PROJECT="${STITCH_GCP_PROJECT:-gold-price-tools-497114}"
SDK_DIR="$HOME/google-cloud-sdk"
STITCH_DIR="$HOME/.stitch"
export CLOUDSDK_CONFIG="${CLOUDSDK_CONFIG:-$HOME/.config/gcloud}"
GCLOUD="$SDK_DIR/bin/gcloud"
ENDPOINT="https://stitch.googleapis.com/mcp"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"

ok()   { printf '  [ok] %s\n' "$*"; }
note() { printf '  [..] %s\n' "$*"; }
warn() { printf '  [!!] %s\n' "$*"; }

printf '== Stitch web setup (identity: %s | project: %s) ==\n' "$STITCH_ACCOUNT" "$GCP_PROJECT"

# ---- 1 & 2. gcloud ---------------------------------------------------------
if "$GCLOUD" --version >/dev/null 2>&1; then
  ok "gcloud present: $("$GCLOUD" --version 2>/dev/null | head -1)"
else
  case "$(uname -s)-$(uname -m)" in
    Linux-x86_64)              ART=google-cloud-cli-linux-x86_64.tar.gz ;;
    Linux-aarch64|Linux-arm64) ART=google-cloud-cli-linux-arm.tar.gz ;;
    Darwin-x86_64)             ART=google-cloud-cli-darwin-x86_64.tar.gz ;;
    Darwin-arm64)              ART=google-cloud-cli-darwin-arm.tar.gz ;;
    *)                         ART=google-cloud-cli-linux-x86_64.tar.gz ;;
  esac
  note "Installing gcloud ($ART) from the storage.googleapis.com mirror ..."
  tmp="$(mktemp -d)"
  if curl -fsS -m 600 -o "$tmp/g.tgz" "https://storage.googleapis.com/cloud-sdk-release/$ART" \
     && tar -xzf "$tmp/g.tgz" -C "$HOME"; then
    rm -rf "$tmp"
    if "$GCLOUD" --version >/dev/null 2>&1; then
      ok "gcloud installed: $("$GCLOUD" --version 2>/dev/null | head -1)"
    else
      warn "gcloud extracted but does not run"; exit 0
    fi
  else
    warn "gcloud download/extract failed (is storage.googleapis.com allowlisted?)"
    rm -rf "$tmp"; exit 0
  fi
fi

# ---- 3. Proxy wrapper + direct helper (no secrets) -------------------------
mkdir -p "$STITCH_DIR"

cat > "$STITCH_DIR/stitch-proxy.sh" <<'WRAP'
#!/usr/bin/env bash
# GENERATED by scripts/stitch-web-setup.sh -- do not edit.
# Launches the Stitch MCP proxy with a freshly minted OAuth token.
export PATH="@SDKBIN@:$PATH"
export CLOUDSDK_CONFIG="@CFG@"
export GOOGLE_CLOUD_PROJECT="@PROJ@"
export STITCH_PROJECT_ID="@PROJ@"
export STITCH_ACCESS_TOKEN="$(gcloud auth print-access-token 2>/dev/null)"
exec npx -y @_davideast/stitch-mcp proxy
WRAP

cat > "$STITCH_DIR/stitch" <<'HELP'
#!/usr/bin/env bash
# GENERATED by scripts/stitch-web-setup.sh -- direct Stitch MCP caller.
# Bypasses the upstream `stitch-mcp tool` subcommand (which crashes on a
# $defs/ScreenInstance schema $ref). The endpoint is a stateless MCP-over-HTTP
# server, so tools/call can be POSTed directly.
# Usage: stitch [tool] [json-args]   (default tool: list_projects)
TOOL="${1:-list_projects}"
if [ -n "${2:-}" ]; then ARGS="$2"; else ARGS='{}'; fi
export PATH="@SDKBIN@:$PATH"
export CLOUDSDK_CONFIG="@CFG@"
TOKEN="$(gcloud auth print-access-token 2>/dev/null)"
curl -m 120 -sS -X POST "@ENDPOINT@" \
  -H "Authorization: Bearer $TOKEN" \
  -H "x-goog-user-project: @PROJ@" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json, text/event-stream" \
  -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"tools/call\",\"params\":{\"name\":\"$TOOL\",\"arguments\":$ARGS}}"
HELP

sed -i \
  -e "s#@SDKBIN@#$SDK_DIR/bin#g" \
  -e "s#@CFG@#$CLOUDSDK_CONFIG#g" \
  -e "s#@PROJ@#$GCP_PROJECT#g" \
  -e "s#@ENDPOINT@#$ENDPOINT#g" \
  "$STITCH_DIR/stitch-proxy.sh" "$STITCH_DIR/stitch"
chmod +x "$STITCH_DIR/stitch-proxy.sh" "$STITCH_DIR/stitch"
ok "proxy + helper generated in $STITCH_DIR"

# ---- 4. .mcp.json (repo root, gitignored) ----------------------------------
cat > "$REPO_ROOT/.mcp.json" <<JSON
{
  "mcpServers": {
    "stitch": {
      "command": "$STITCH_DIR/stitch-proxy.sh"
    }
  }
}
JSON
ok ".mcp.json written at repo root"

if ! grep -qxF ".mcp.json" "$REPO_ROOT/.gitignore" 2>/dev/null; then
  printf '\n# Stitch MCP local config (machine-specific; never commit)\n.mcp.json\n' >> "$REPO_ROOT/.gitignore"
  ok "added .mcp.json to .gitignore"
else
  ok ".mcp.json is gitignored"
fi

# ---- 5 & 6. Auth + API status (never prints tokens) ------------------------
ACTIVE="$("$GCLOUD" auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -1)"
if [ -z "$ACTIVE" ]; then
  warn "No gcloud login found -- ONE manual browser consent is required:"
  cat <<MSG

    Sign in as $STITCH_ACCOUNT (NOT the digitalcliqs login):

      CLOUDSDK_CONFIG="$CLOUDSDK_CONFIG" "$GCLOUD" auth login --no-launch-browser

    Open the printed URL in an Incognito window, choose $STITCH_ACCOUNT,
    approve "Google Cloud SDK", then paste the verification code.
    In Claude Code on the web, just ask Claude to "log in to Stitch" and it
    will relay the URL and feed your code back into the flow automatically.
MSG
else
  if [ "$ACTIVE" = "$STITCH_ACCOUNT" ]; then
    ok "Authenticated as $ACTIVE"
  else
    warn "Authenticated as $ACTIVE (expected $STITCH_ACCOUNT). To switch:"
    note "\"$GCLOUD\" auth login --no-launch-browser   # then pick $STITCH_ACCOUNT"
  fi
  "$GCLOUD" config set project "$GCP_PROJECT" >/dev/null 2>&1
  if "$GCLOUD" services list --enabled --project="$GCP_PROJECT" \
        --filter="config.name:stitch.googleapis.com" \
        --format='value(config.name)' 2>/dev/null | grep -q stitch; then
    ok "stitch.googleapis.com enabled on $GCP_PROJECT"
  else
    note "Enabling stitch.googleapis.com on $GCP_PROJECT ..."
    if "$GCLOUD" services enable stitch.googleapis.com --project="$GCP_PROJECT" >/dev/null 2>&1; then
      ok "stitch.googleapis.com enabled on $GCP_PROJECT"
    else
      warn "Could not enable stitch.googleapis.com (need serviceusage rights as $STITCH_ACCOUNT)"
    fi
  fi
fi

printf '== Stitch web setup complete ==\n'
exit 0
